# Generated by Django 4.2.6 on 2023-10-27 14:39

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(db_index=True, verbose_name='Внешний id в системе маркетплейса')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipient_categories', to='common.marketplace', verbose_name='Маркетплейс-получатель')),
                ('parent_categories', models.ManyToManyField(related_name='children', to='recipient.category', verbose_name='Родительские категории')),
            ],
            options={
                'verbose_name': 'Категория в системе получателя',
                'verbose_name_plural': 'Категории в системе получателя',
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(db_index=True, verbose_name='Внешний id в системе получателя')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательная характеристика')),
                ('categories', models.ManyToManyField(related_name='characteristics', to='recipient.category', verbose_name='Категории в системе получателя')),
            ],
            options={
                'verbose_name': 'Характеристика товара с системе получателя',
                'verbose_name_plural': 'Характеристики товара в системе получателя',
            },
        ),
        migrations.CreateModel(
            name='CharacteristicValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(db_index=True, verbose_name='Внешний id в системе получателя')),
                ('value', models.CharField(max_length=200, verbose_name='Значение')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_values', to='recipient.characteristic', verbose_name='Характеристика в системе получателя')),
            ],
            options={
                'verbose_name': 'Значение характеристики в системе получателя',
                'verbose_name_plural': 'Значения характеристики в системе получателя',
            },
        ),
    ]
