# Generated by Django 4.2.6 on 2023-10-29 05:19

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('recipient', '0003_alter_category_parent_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='marketplace',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='recipient_characteristics', to='common.marketplace', verbose_name='Маркетплейс-получатель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characteristicvalue',
            name='marketplace',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='recipient_characteristic_values', to='common.marketplace', verbose_name='Маркетплейс-получатель'),
            preserve_default=False,
        ),
    ]
