# Generated by Django 4.2.6 on 2023-11-02 22:12

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0004_characteristic_marketplace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_categories',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='recipient.category', verbose_name='Родительские категории'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание характеристики'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='has_reference_values',
            field=models.BooleanField(default=False, verbose_name='Имеет ссылочные значения'),
        ),
    ]
