# Generated by Django 4.2.6 on 2023-11-13 15:24

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0005_remove_category_parent_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristicvalue',
            name='value',
            field=models.TextField(verbose_name='Значение'),
        ),
    ]
