# Generated by Django 4.2.6 on 2023-11-15 11:22

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0007_alter_characteristicvalue_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='recipient.category', verbose_name='Родительская категория'),
        ),
        migrations.CreateModel(
            name='CharacteristicForCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательная характеристика')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipient.category', verbose_name='Категория в системе поставщика')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipient.characteristic', verbose_name='Характеристика в системе поставщика')),
            ],
            options={
                'verbose_name': 'Связь категория-характеристика',
                'verbose_name_plural': 'Связи категория-характеристика',
            },
        ),
        migrations.AddField(
            model_name='characteristic',
            name='categories',
            field=models.ManyToManyField(related_name='characteristics', through='recipient.CharacteristicForCategory', to='recipient.category', verbose_name='Категории в системе получателя'),
        ),
    ]
