# Generated by Django 4.2.6 on 2023-10-27 14:39

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('url', models.URLField(verbose_name='URL товара')),
                ('is_allowed_import', models.BooleanField(default=False, verbose_name='Разрешение для импорта')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_products', to='common.marketplace', verbose_name='Маркетплейс-поставщик')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='RawCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('url', models.URLField(verbose_name='URL товара')),
                ('is_allowed_import', models.BooleanField(default=False, verbose_name='Разрешение для импорта')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_categories', to='common.marketplace', verbose_name='Маркетплейс-поставщик')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
