# Generated by Django 4.2.6 on 2023-11-12 17:10

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('parser_targets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawcategory',
            name='url',
            field=models.URLField(verbose_name='URL категории/поиска'),
        ),
    ]
