# Generated by Django 4.2.6 on 2023-10-27 14:39

from decimal import (
    Decimal,
)

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)

import provider.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('recipient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='Внешний id в системе маркетплейса')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('translated_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Переведённое наименование')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_categories', to='common.marketplace', verbose_name='Маркетплейс-поставщик')),
                ('recipient_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_categories', to='recipient.category', verbose_name='Категория получателя')),
            ],
            options={
                'verbose_name': 'Категория с системе поставщика',
                'verbose_name_plural': 'Категории в системе поставщика',
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(db_index=True, verbose_name='Внешний id в системе маркетплейса')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('translated_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Переведённое наименование')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательная характеристика')),
                ('categories', models.ManyToManyField(related_name='characteristics', to='provider.category', verbose_name='Категории в системе поставщика')),
                ('recipient_characteristic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_characteristics', to='recipient.characteristic', verbose_name='Характеристика в системе поставщика')),
            ],
            options={
                'verbose_name': 'Характеристика товара с системе поставщика',
                'verbose_name_plural': 'Характеристики товара в системе поставщика',
            },
        ),
        migrations.CreateModel(
            name='CharacteristicValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(db_index=True, verbose_name='Внешний id в системе поставщика')),
                ('value', models.CharField(max_length=200, verbose_name='Значение')),
                ('translated_value', models.CharField(blank=True, max_length=100, null=True, verbose_name='Переведённое значение')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_values', to='provider.characteristic', verbose_name='Характеристика в системе поставщика')),
                ('recipient_characteristic_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_characteristic_values', to='recipient.characteristicvalue', verbose_name='Значение характеристики в системе поставщика')),
            ],
            options={
                'verbose_name': 'Значение характеристики в системе поставщика',
                'verbose_name_plural': 'Значения характеристики в системе поставщика',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(db_index=True, verbose_name='Внешний id в системе поставщика')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('translated_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Переведённое наименование')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
                ('translated_description', models.TextField(blank=True, null=True, verbose_name='Переведенное описание')),
                ('url', models.URLField(verbose_name='URL товара')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Цена')),
                ('discounted_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Цена со скидкой')),
                ('import_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('upload_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата выгрузки')),
                ('status', models.BooleanField(default=False, verbose_name='Разрешение для экспорта')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='provider.category', verbose_name='Категория в системе поставщика')),
            ],
            options={
                'verbose_name': 'Товар с системе поставщика',
                'verbose_name_plural': 'Товары с системе поставщика',
            },
        ),
        migrations.CreateModel(
            name='ProductValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.product', verbose_name='Товар')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.characteristicvalue', verbose_name='Значение')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=provider.models.collect_image_path, verbose_name='Изображение товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='provider.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товара',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic_values',
            field=models.ManyToManyField(related_name='products', through='provider.ProductValue', to='provider.characteristicvalue', verbose_name='Значение характеристики в системе поставщика'),
        ),
    ]
