# Generated by Django 4.2.6 on 2023-10-27 19:22

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='external_id',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Внешний id в системе маркетплейса'),
        ),
    ]
