# Generated by Django 4.2.6 on 2023-10-28 11:10

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_alter_category_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='translated_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Переведённое наименование'),
        ),
        migrations.AlterField(
            model_name='characteristicvalue',
            name='translated_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Переведённое значение'),
        ),
        migrations.AlterField(
            model_name='characteristicvalue',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='translated_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Переведённое наименование'),
        ),
    ]
