# Generated by Django 4.2.6 on 2023-11-02 17:36

from django.db import (
    migrations,
)


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_characteristic_marketplace_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='is_export_allowed',
        ),
    ]
