# Generated by Django 4.2.6 on 2023-11-04 05:57

from django.db import (
    migrations,
)


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_rename_status_product_is_export_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='recipient_category',
        ),
        migrations.RemoveField(
            model_name='characteristic',
            name='recipient_characteristic',
        ),
        migrations.RemoveField(
            model_name='characteristicvalue',
            name='recipient_characteristic_value',
        ),
    ]
