# Generated by Django 4.2.6 on 2023-11-10 09:22

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_characteristicmatching_recipient_value_and_more'),
        ('provider', '0006_remove_category_recipient_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristicvalue',
            options={'verbose_name': 'Значение характеристики в системе поставщика', 'verbose_name_plural': 'Значения характеристик в системе поставщика'},
        ),
        migrations.RemoveField(
            model_name='characteristic',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='translated_description',
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Код товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, verbose_name='Количество в наличии'),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(db_index=True, verbose_name='Внешний id в системе поставщика')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_brands', to='common.marketplace', verbose_name='Маркетплейс-поставщик')),
            ],
            options={
                'verbose_name': 'Бренд в системе поставщика',
                'verbose_name_plural': 'Бренды с системе поставщика',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='provider.brand', verbose_name='Бренд'),
        ),
    ]
