# Generated by Django 4.2.6 on 2023-11-12 17:10

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0007_alter_characteristicvalue_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=3000, verbose_name='URL товара'),
        ),
    ]
