# Generated by Django 4.2.6 on 2023-11-16 19:16

from decimal import (
    Decimal,
)

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0009_product_markup'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6, verbose_name='Вес товара, кг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='markup',
            field=models.PositiveIntegerField(default=100, verbose_name='Коэффициент наценки стоимости товара, %'),
        ),
    ]
