# Generated by Django 4.2.6 on 2023-11-30 09:07

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0011_product_is_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='markup',
            field=models.PositiveIntegerField(default=60, verbose_name='Коэффициент наценки стоимости товара, %'),
        ),
    ]
