# Generated by Django 4.2.6 on 2023-12-13 19:30

from decimal import (
    Decimal,
)

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0014_product_depth_product_height_product_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='depth',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6, verbose_name='Глубина, см'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6, verbose_name='Высота, см'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6, verbose_name='Ширина, см'),
        ),
    ]
