# Generated by Django 4.2.6 on 2023-12-29 06:39

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0008_alter_category_parent_category_and_more'),
        ('provider', '0016_characteristicvalue_recipient_characteristic_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristicvalue',
            name='recipient_characteristic_value',
        ),
        migrations.AddField(
            model_name='characteristicvalue',
            name='recipient_characteristic_values',
            field=models.ManyToManyField(blank=True, related_name='provider_characteristic_values', to='recipient.characteristicvalue', verbose_name='Значения характеристики в системе получателя'),
        ),
    ]
