# Generated by Django 4.2.6 on 2024-02-05 07:45

from django.db import (
    migrations,
)


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0019_alter_product_markup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар в системе поставщика', 'verbose_name_plural': 'Товары в системе поставщика'},
        ),
    ]
