# Generated by Django 4.2.6 on 2024-02-09 17:17

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0019_alter_product_markup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар в системе поставщика', 'verbose_name_plural': 'Товары в системе поставщика'},
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Активный'), (2, 'Архивирован')], default=1, verbose_name='Статус'),
        ),
    ]
