# Generated by Django 4.2.6 on 2024-04-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0020_alter_product_options_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='external_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Внешний id в системе маркетплейса'),
        ),
    ]
