# Generated by Django 4.2.6 on 2023-10-27 14:39

from decimal import (
    Decimal,
)

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование валюты')),
                ('code', models.CharField(max_length=3, verbose_name='Код валюты')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='SystemSettingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3, verbose_name='Коэффициент наценки стоимости товаров')),
                ('is_selected', models.BooleanField(default=False, verbose_name='Активная конфигурация')),
            ],
            options={
                'verbose_name': 'Конфигурация системы',
                'verbose_name_plural': 'Конфигурации системы',
            },
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('url', models.URLField(verbose_name='URL маркетплейса')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Поставщик'), (2, 'Получатель')], verbose_name='Тип')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplaces', to='common.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Маркетплейс',
                'verbose_name_plural': 'Маркетплейсы',
            },
        ),
    ]
