# Generated by Django 4.2.6 on 2023-11-04 05:57

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_remove_category_recipient_category_and_more'),
        ('recipient', '0005_remove_category_parent_categories_and_more'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matchings', to='provider.category', verbose_name='Категория поставщика')),
                ('recipient_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchings', to='recipient.category', verbose_name='Категория получателя')),
            ],
            options={
                'verbose_name': 'Сопоставление категорий',
                'verbose_name_plural': 'Сопоставления категорий',
            },
        ),
        migrations.CreateModel(
            name='CharacteristicMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='"Сырое" значение')),
                ('category_matching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_matchings', to='common.categorymatching', verbose_name='Сопоставление категорий')),
                ('provider_characteristic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider.characteristic', verbose_name='Характеристика получателя')),
                ('recipient_characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipient.characteristic', verbose_name='Характеристика получателя')),
                ('recipient_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characteristic_matchings', to='recipient.characteristicvalue', verbose_name='Значение в системе получателя')),
            ],
            options={
                'verbose_name': 'Сопоставление характеристик',
                'verbose_name_plural': 'Сопоставления характеристик',
            },
        ),
        migrations.CreateModel(
            name='CharacteristicValueMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic_matching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_matchings', to='common.characteristicmatching', verbose_name='Сопоставление характеристик')),
                ('provider_characteristic_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider.characteristicvalue', verbose_name='Значение поставщика')),
                ('recipient_characteristic_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchings', to='recipient.characteristicvalue', verbose_name='Значение получателя')),
            ],
            options={
                'verbose_name': 'Сопоставление значений характеристик',
                'verbose_name_plural': 'Сопоставления значений характеристик',
            },
        ),
    ]
