# Generated by Django 4.2.6 on 2023-11-04 06:05

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_categorymatching_characteristicmatching_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristicmatching',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='"Сырое" значение'),
        ),
    ]
