# Generated by Django 4.2.6 on 2023-11-04 20:59

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_remove_category_recipient_category_and_more'),
        ('common', '0005_alter_characteristicmatching_recipient_characteristic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymatching',
            name='provider_category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matching', to='provider.category', verbose_name='Категория поставщика'),
        ),
    ]
