# Generated by Django 4.2.6 on 2023-11-06 10:16

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_remove_category_recipient_category_and_more'),
        ('recipient', '0005_remove_category_parent_categories_and_more'),
        ('common', '0007_remove_characteristicmatching_recipient_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristicmatching',
            name='recipient_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characteristic_matchings', to='recipient.characteristicvalue', verbose_name='Значение в системе получателя'),
        ),
        migrations.AlterField(
            model_name='characteristicvaluematching',
            name='provider_characteristic_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchings', to='provider.characteristicvalue', verbose_name='Значение поставщика'),
        ),
    ]
