# Generated by Django 4.2.6 on 2023-11-13 15:24

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_characteristicmatching_recipient_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettingconfig',
            name='markup',
        ),
        migrations.AddField(
            model_name='systemsettingconfig',
            name='vat_rate',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ставка НДС, %'),
        ),
    ]
