# Generated by Django 4.2.6 on 2023-11-14 13:52

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_remove_systemsettingconfig_markup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, verbose_name='Наименование сервиса')),
                ('entry', models.TextField(verbose_name='Запись')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'Логи',
                'verbose_name_plural': 'Записи в логах',
            },
        ),
        migrations.CreateModel(
            name='SystemEnvironment',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Ключ')),
                ('value', models.TextField(verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Системная переменная',
                'verbose_name_plural': 'Системные переменные',
            },
        ),
    ]
