# Generated by Django 4.2.6 on 2023-11-15 09:17

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_log_systemenvironment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettingconfig',
            name='vat_rate',
            field=models.CharField(choices=[('0', 'Не облагается'), ('0.1', '10%'), ('0.2', '20%')], default='0', verbose_name='Ставка НДС'),
        ),
    ]
