# Generated by Django 4.2.6 on 2023-11-16 11:33

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_characteristicmatching_recipient_characteristic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Курс')),
                ('rate_datetime', models.DateTimeField(verbose_name='Последнее время обновления курса')),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='destination_exchange_rate', to='common.currency', verbose_name='Валюта назначения')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source_exchange_rates', to='common.currency', verbose_name='Исходная валюта')),
            ],
            options={
                'verbose_name': 'Курс валют',
                'verbose_name_plural': 'Курсы валют',
            },
        ),
    ]
