# Generated by Django 4.2.6 on 2023-11-17 19:40

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_alter_marketplace_currency_logistics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_exchange_rate', to='common.currency', verbose_name='Валюта назначения'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_exchange_rates', to='common.currency', verbose_name='Исходная валюта'),
        ),
    ]
