# Generated by Django 4.2.6 on 2023-12-03 18:07

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_alter_exchangerate_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalArea',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Наименование')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_areas', to='common.marketplace', verbose_name='Маркетплейс')),
            ],
            options={
                'verbose_name': 'Личный кабинет',
                'verbose_name_plural': 'Личные кабинеты',
            },
        ),
        migrations.CreateModel(
            name='PersonalAreaVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_variables', to='common.personalarea')),
            ],
            options={
                'verbose_name': 'Переменная личного кабинета',
                'verbose_name_plural': 'Переменные личных кабинетов',
            },
        ),
        migrations.CreateModel(
            name='SystemVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='Ключ')),
                ('value', models.TextField(verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Системная переменная',
                'verbose_name_plural': 'Системные переменные',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('external_id', models.PositiveIntegerField(verbose_name='Внешний идентификатор')),
                ('personal_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.personalarea')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.DeleteModel(
            name='SystemEnvironment',
        ),
        migrations.AddField(
            model_name='personalareavariable',
            name='system_variable',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_personal_areas', to='common.systemvariable'),
        ),
        migrations.AddField(
            model_name='systemsettingconfig',
            name='system_variables',
            field=models.ManyToManyField(related_name='system_setting_configs', to='common.systemvariable', verbose_name='Системные переменные'),
        ),
    ]
