# Generated by Django 4.2.6 on 2023-12-03 18:58

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_personalarea_personalareavariable_systemvariable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='external_id',
            field=models.PositiveBigIntegerField(verbose_name='Внешний идентификатор'),
        ),
    ]
