# Generated by Django 4.2.6 on 2024-01-16 20:34

from decimal import (
    Decimal,
)

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_alter_warehouse_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics',
            name='markup',
            field=models.PositiveIntegerField(default=0, verbose_name='Логистическая наценка, %'),
        ),
        migrations.AddField(
            model_name='logistics',
            name='shipment_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Стоимость отправления'),
        ),
        migrations.AddField(
            model_name='systemsettingconfig',
            name='default_markup',
            field=models.PositiveIntegerField(default=60, verbose_name='Коэффициент наценки стоимости товара по умолчанию, %'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logistics',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Стоимость логистики за 100 г'),
        ),
    ]
