# Generated by Django 4.2.6 on 2024-04-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_logistics_markup_logistics_shipment_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YarvetProductMatchings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Артикул в ярвет')),
                ('external_id', models.IntegerField(db_index=True, unique=True, verbose_name='Идентификатор в ярвет')),
            ],
            options={
                'verbose_name': 'Сопоставление артикула и идентификатора товара',
                'verbose_name_plural': 'Сопоставления артикулов и идентификаторов товаров',
            },
        ),
    ]
