# Generated by Django 4.2.6 on 2024-04-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_logistics_markup_logistics_shipment_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='type',
            field=models.CharField(choices=[('GLOBAL', 'Глобальный'), ('CUSTOM', 'Пользовательский')], default='GLOBAL', verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
