# Generated by Django 4.2.6 on 2024-04-21 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_warehouse_type'),
        ('common', '0019_yarvetproductmatchings'),
    ]

    operations = [
    ]
