BLANK_VALUE_FOR_UPDATE_MESSAGE = 'Пожалуйста, укажите значение для обновления товаров.'
UPDATE_PRODUCT_IS_SUCCESS = 'Товары успешно обновлены!'
ARCHIVE_PRODUCT_IS_SUCCESS = 'Товары успешно архивированы!'
LOAD_PRODUCT_IS_SUCCESS = 'Товары отправлены на выгрузку!'
COMPARE_PRODUCT_CHARACTERISTICS_IS_SUCCESS = 'Атрибуты товаров сопоставлены!'